# Generated by Django 3.2.5 on 2021-07-25 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20210725_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
    ]
