# Generated by Django 3.2.5 on 2021-07-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(default='Harshita ki chudai', max_length=128),
            preserve_default=False,
        ),
    ]
