# Generated by Django 3.2.5 on 2021-09-16 10:02

from django.db import migrations, models
import tracker.models
import tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=tracker.models.expense_attachment, validators=[tracker.validators.validate_attachment]),
        ),
    ]
